# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Compile LaTeX for day1
        uses: xu-cheng/latex-action@v2
        with:
          working-directory: day1
          root_file: ./day1.tex
          latexmk_use_lualatex: true
      
      # Runs a single command using the runners shell
      - name: Compile LaTeX for day2
        uses: xu-cheng/latex-action@v2
        with:
          working-directory: day2
          root_file: ./day2.tex
          latexmk_use_lualatex: true
      
      - run: mv ./day1/day1.pdf ./www/day1.pdf
      - run: mv ./day2/day2.pdf ./www/day2.pdf
        
      - name: Deploy Web Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
